server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdemo?characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
   #连接池支持的最大连接数
    max-active: 20
    initial-size: 1
    # 最大连接池数量
    max-idle: 30
    # 最小连接池数量
    min-idle: 5
    # 获取连接时最大等待时间，单位毫秒
    max-wait: 60000
  redis:
    host : 127.0.0.1
    port : 6379
    database : 1
    pool.max-idle : 8
    pool.min-idle : 1
    pool.max-active : 8
    pool.max-wait : -1
mybatis:
  mapper-locations: classpath:mappers/*.xml #定义xml文件位置，不是必须的，如果需要在xml写sql请配置此选项
  type-aliases-package: com.hui.pojo.*
  configuration:
    mapUnderscoreToCamelCase: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                 # 注意：对应实体类的路径
mapper:
  mappers: com.hui.mapper.BaseMapper #通用基类配置
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
time:
  cron: 0 0 21 * * ?


